### PR TITLE
fix Android 11 email intent params & targets

### PR DESCRIPTION
**Pull request by pprattis**
Fixes Android 11 target sdk 30 crash, fixes email intent params and now can successfully attach multiple files, pop up menu shows the correct target apps.

### CODE REVIEW

**Comment by jfoclpf** [comment]
@katzer do you know when and if you will publish these changes to npm?

**Comment by jfoclpf** [comment]
@PetePrattis  I have the same problem, it crashes in Android 11, how did you manage this? Why did you close the PR?

**Comment by PetePrattis** [comment]
@jfoclpf Well my pr was a workaround, this pr #361 seems to be the actual solution, worked for me.

**Comment by jfoclpf** [comment]
@PetePrattis could you kindly tell me in #365 what is exactly the solution? Thanks

**Comment by jfoclpf** [comment]
@PetePrattis do you mean PR #368 is the stable solution?

**Comment by PetePrattis** [comment]
@jfoclpf Yes sorry, I meant #368, the one that I use for my production.

**Comment by jfoclpf** [comment]
@PetePrattis can I ask you exactly how did you implement it in production since this project seems to be abandoned? 

Did you fork it and fetched from your own repo?

**Pull request closed without merging**
