### PR TITLE
Add support for an app:// URL

### PR DESCRIPTION
**Pull request by shankari**
This will read data from the app's private dir ('/data/data/<app_pkg_name') in the emulator, which includes the following directories.
    - app_database
    - app_webview
    - cache
    - databases
    - files
    - lib
    - shared_prefs

### CODE REVIEW

**Comment by shankari** [comment]
Resubmitting without the merge commit

**Comment by katzer** [comment]
@shankari Thanks for your PR. I don't see a common use case to make private directories available.

**Comment by shankari** [comment]
@katzer the use case, and the reason I added the PR, is to email sqlite databases. These are typically created in the private directory and are inaccessible otherwise. Adding support for private directories allows developers who use sqlite to store data (very common) to allow users to email them, e.g. for debugging.

**Comment by katzer** [comment]
@shankari It's why I wrote that "I don't see a common use case"

I will take a look into the code. I wont allow to access private folders by default. But maybe if a property flag has been set. However that can be added by any other plugin without notice...

**Comment by shankari** [comment]
@katzer, just to clarify, although it is called the _private_ directory, it is the recommended location for apps to store information, and is considered the most safe to use. So safe, in fact, that 
> No additional permissions are required for the calling app to read or write files under the returned path.

https://developer.android.com/reference/android/content/ContextWrapper.html#getFilesDir()

**Pull request merged**
