### PR TITLE
Fixes build error on cordova-ios-4.x (backwards compatible)

### PR DESCRIPTION
**Pull request by shazron**

### CODE REVIEW

**Comment by vood** [comment]
Since I don't have access to this repo I've forked it and merged this PR. It works thanks! You can find it here https://github.com/ConnectCorp/cordova-plugin-email-composer

**Comment by Edwardzyc** [comment]
Will this ever be merged?

**Comment by edismooth** [comment]
+1
Merge it please.

**Comment by katzer** [comment]
I've merged #169 which includes this PR - Thanks!

**Pull request closed without merging**
