### PR TITLE
Added BlackBerry10 support

### PR DESCRIPTION
**Pull request by dielsonsales**
Added support for BlackBerry >= 10.0

### CODE REVIEW

**Comment by katzer** [comment]
@dielsonsales BTW many thanks for your BB10 support. I am personally a BB user. But since they don't even update their API docs nor support developers I am don't feel the willing to add BB10. Its also marked as deprecated already.

**Comment by dielsonsales** [comment]
I'm also not working for BlackBerry anymore, so I wouldn't have time to support this anyway. Feel free to close this PR.

**Comment by katzer** [comment]
You have been an employee of BlackBerry?

**Comment by dielsonsales** [comment]
Not an official employee, but during my university time I worked in a project where we were paid by BlackBerry for about 2 years to develop native apps & plugins for BlackBerry 10.

**Comment by katzer** [comment]
The good old time...

**Pull request closed without merging**
