### PR TITLE
Calling .open() crushes the app with targetSdk set to 30 on Android 

### PR DESCRIPTION
**Pull request by AliMariam**

### CODE REVIEW

**Comment by jfoclpf** [comment]
Thank you very much @AliMariam  for the PR, but according to the conversation in #372 (comment from @ahmad-alkhatib ) this does not seem to solve the problem

**Comment by jfoclpf** [comment]
@AliMariam 
Have you made tests yourself that this solves the problem?

**Comment by AliMariam** [comment]
yes @jfoclpf  i have tested the solution on many devices in production mode , and it works perfectly
`Samsung Galaxy A52S 5G , Android version : 12
Honor 8X, Android Version; 10
Huawei P30 Lite, Android Version; 10
HUAWEI Y5, Android Version;  8.2.0
Poco X3 Pro, Android : 12.1
Samsung Galaxy S20, Android 12
oppo a5s Android V8.1.0
HUAWEI Y5, Android Version;  8.0.0`

**Comment by jfoclpf** [comment]
Thanks @AliMariam , just a further question

did you test before and after this change? To be sure that this change you make solves the problem we're facing.

If not, could you kindly test again but without the change with Android 12, to be sure the crash really happens?

I'm saying this, because if we see no differences with the change, there's no need to change.

Thanks again for your cooperation

**Comment by AliMariam** [comment]
@jfoclpf  I confirm that my test in android 12 was before and after update i made on the code

**Review by HAFSADEV1 — APPROVED** [review]

**Review by issaouiyasmine — APPROVED** [review]

**Comment by jfoclpf** [comment]
Thanks @AliMariam merged accordingly then

**Pull request merged**
