### PR TITLE
updated FileProvider import to use androidx

### PR DESCRIPTION
**Pull request by adityasingh0208**
Fix to issue [#348 ](https://github.com/katzer/cordova-plugin-email-composer/issues/348)

### CODE REVIEW

**Comment by marioshtika** [comment]
Is this pull request going to be accepted?

**Comment by capc0** [comment]
@adityasingh0208 do you have this fix published (or can you do so) under a different npm name? would be awesome!

**Comment by Yadro** [comment]
@katzer could you please merge this PR?

**Comment by Kazanian2** [comment]
@katzer @PKnittel @bboybboy @mdomi @ywplee 
Could somebody please merge this?
Thanks!

**Comment by katzer** [comment]
thanks

**Pull request merged**
